add first autograded assignment
replit/replit.github.io pull request #63
Opened 2020-09-18 17:39 UTC by sixhobbits

2020-09-25 17:23 UTC, jeremypress commented on classrooms/teams_for_education.md
> +We've written a tutorial for how to do testing in Python using PyTest that you can read [here](https://docs.repl.it/tutorials/09-test-driven-development).
mind fixing the spelling of "assessments" just above here?

2020-09-25 17:23 UTC, jeremypress commented on teachers/first-autograded-assignment.md
> +### Understanding templates
This is really good content, but it shouldn't be hidden behind autograding instructions. Can you consolidate this with the base teams docs and then just point to it here for the case where teachers are unfamiliar with the concepts?

2020-09-25 17:23 UTC, jeremypress commented on teachers/first-autograded-assignment.md
> +If you need to provide more comprehensive instructions you can create a [markdown](https://en.wikipedia.org/wiki/Markdown) file from within the repl by pressing the `add file` button in the files pan
nit: if you name the file readme.md we'll render it first when a student opens the workspace, so you'll be greeted with the instructions.

2020-09-25 17:23 UTC, jeremypress commented on teachers/first-autograded-assignment.md
> +## Viewing all submissions as a teacher
this also feels teams for education generic. We would want teachers to be exposed to this kind of content even if they are not using autograding.

2020-09-25 22:45 UTC, sixhobbits commented on sidebar.json
> +    "name": "Teachers",
I could only find the "Classrooms" section and Patrick said I should create this one instead?

2020-09-25 22:46 UTC, sixhobbits commented on teachers/first-autograded-assignment.md
> +Autograding is done by having unit tests automatically execute your students' code with pre-specified inputs and check if the outputs are as expected.
just checking I understood here - you mean replace that sentence with your version? Done that.

2020-09-25 22:48 UTC, sixhobbits commented on teachers/first-autograded-assignment.md
> +### Understanding templates
As this is an intro guide I think it would be really cool if it were self contained as I know from experience that a lot of people "drop off" at the moment they have to navigate somewhere else to find something before coming back again. Mind if I add a separate more generic guide for Teams to supplement this and then keep this + the next similar one you mentioned in this guide to keep it easy to follow?

2020-09-26 01:56 UTC, jeremypress commented on sidebar.json
> +    "name": "Teachers",
try rebasing, I think Obaida added some new stuff

2020-09-26 01:57 UTC, jeremypress commented on teachers/first-autograded-assignment.md
> +### Understanding templates
totally cool, I think Obaida laid out a skeleton for that, so we can take your content here and move that in going forward.

2020-09-26 01:58 UTC, jeremypress reviewed
Looks like Obaida added a teams for education section, let's move the autograding stuff there and then looks good!

2020-09-28 21:03 UTC, jeremypress requested changes
a duplicate file + i think we should follow up with a PR for autograding.

2020-09-28 21:03 UTC, jeremypress commented on teachers/first-autograded-assignment.md
> +# Create your first autograded Python homework with Repl.it
this should be removed now that it's under teams as well

2020-09-28 21:03 UTC, jeremypress commented on Teams/building-centralized-autograder.md
> +# Building a centralised autograder with Repl.it
can we do this one in a separate PR? I think there are a few things around privacy that might not be correct, for example, setting a team repl to private will not prevent team members from viewing it.

2020-09-28 21:07 UTC, sixhobbits commented on classrooms/teams_for_education.md
> +We've written a tutorial for how to do testing in Python using PyTest that you can read [here](https://docs.repl.it/tutorials/09-test-driven-development).
done

2020-09-28 21:07 UTC, sixhobbits commented on sidebar.json
> +    "name": "Teachers",
makes sense.

2020-09-28 21:07 UTC, sixhobbits commented on teachers/first-autograded-assignment.md
> +If you need to provide more comprehensive instructions you can create a [markdown](https://en.wikipedia.org/wiki/Markdown) file from within the repl by pressing the `add file` button in the files pan
done.

2020-09-28 21:08 UTC, sixhobbits commented on teachers/first-autograded-assignment.md
> +## Viewing all submissions as a teacher
addressed above.

2020-09-28 21:19 UTC, sixhobbits commented on teachers/first-autograded-assignment.md
> +# Create your first autograded Python homework with Repl.it
done

2020-09-28 21:20 UTC, sixhobbits commented on Teams/building-centralized-autograder.md
> +# Building a centralised autograder with Repl.it
removed.

2020-09-28 23:44 UTC, jeremypress approved these changes
:pencil2:

2020-09-30 11:49 UTC, closed without merging