Oh my....
replit/replit.github.io pull request #65
Opened 2020-09-25 23:35 UTC by pieromqwerty

- Fixed teams folder punctuation
- Grammar and spelling fixes for tutorials folder.
- Piero can no longer look at the tutorials without feeling exhausted.
- Made general grammar more professional.

2020-09-26 01:56 UTC, jeremypress requested changes
Thanks for touching these up! Just a couple small tweaks and we can :boat:

2020-09-26 01:56 UTC, jeremypress commented on teams/roles.md
> +Member -> This is anyone that gets invited is immediately given this role. They are essentially a student.
while you're here. Can you fix up this first sentence? -> Anyone that is invited to the team starts with this role.

2020-09-26 01:56 UTC, jeremypress commented on teams/invitations.md
> +If you have already created a team, go to the team dashboard and under "Teammates" click "Add more."
nothing wrong with conjunctions imo, we have a professional but casual and playful tone in our comms.

2020-09-26 01:56 UTC, jeremypress commented on teams/invitations.md
> +## Inviting People to your Team
can you fix this for privacy invite links too?

2020-09-29 18:46 UTC, pieromqwerty commented on teams/invitations.md
> +If you have already created a team, go to the team dashboard and under "Teammates" click "Add more."
I'll go ahead and change those.

2020-09-29 18:46 UTC, pieromqwerty commented on teams/invitations.md
> +## Inviting People to your Team
Sure thing!

2020-09-29 18:54 UTC, pieromqwerty commented
@jeremypress Should be all done!

2020-12-14 16:52 UTC, closed without merging